function kbg() {
  local theme="$1"
  local kitty_dir="$HOME/.config/kitty"
  local bg_conf="$kitty_dir/current-background.conf"
  local wallpaper_dir="$kitty_dir/wallpapers/"

  if [ ! -d "$wallpaper_dir" ]; then
    echo "No wallpaper directory found at $wallpaper_dir"
    return 1
  fi

  local themes="$(ls $wallpaper_dir | grep -Eo '^[^\.]+')"

  if [ -z "$theme" ]; then
    echo "none"
    echo "$themes"
    return 0
  fi

  if [ "$theme" = "none" ]; then
    rm "$bg_conf"
  else
    local theme_file="$(ls $wallpaper_dir | grep $theme)"
    local theme_opts=$(basename "$theme_file" .png | awk 'BEGIN {FS="."};{print $2}')
    local linear_opt=$(echo "$theme_opts" | grep -Eo 'l')
    local tint_opt=$(echo "$theme_opts" | grep -Eo '\d{1,2}')

    echo "# file generated by kbg" > "$bg_conf"
    echo "# https://sw.kovidgoyal.net/kitty/conf/#color-scheme" >> "$bg_conf"
    echo "" >> "$bg_conf"
    echo "background #000000" >> "$bg_conf"
    echo "color0 #000000" >> "$bg_conf"
    echo "active_tab_foreground   #000000" >> "$bg_conf"
    echo "inactive_tab_background #000000" >> "$bg_conf"
    echo "" >> "$bg_conf"
    echo "background_image wallpapers/$theme_file" >> "$bg_conf"
    echo "background_image_layout cscaled" >> "$bg_conf"
    if [ -n "$linear_opt" ]; then
      echo "background_image_linear yes" >> "$bg_conf"
    fi
    if [ -n "$tint_opt" ]; then
      echo "background_tint 0.$tint_opt" >> "$bg_conf"
    fi
  fi

  kill -SIGUSR1 $(pgrep -a kitty)
}

function _complete_kbg() {
  COMPREPLY="$(kbg)"
}

complete -F _complete_kbg kbg
