#+title: Emacs Configuration
#+author: jdeyerle
#+property: header-args:emacs-lisp :tangle ./.config.el
#+startup: content
#+startup: indent

* Package Management

Set up ELPA, MELPA, and Org package repositories and load [[https://github.com/jwiegley/use-package][use-package]] to manage package configuration.

#+begin_src emacs-lisp
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package-ensure)
(setq use-package-always-ensure t)
#+end_src

* Keep .emacs.d Clean

Move transient files elsewhere so they don't show up as untracked in the Git repo. Load [[https://github.com/emacscollective/no-littering][no-littering]] and [[https://github.com/larstvei/Try][try]] to make this a bit easier.

#+begin_src emacs-lisp
(setq  user-emacs-directory (expand-file-name "~/.cache/emacs/")
       url-history-file (expand-file-name "url/history" user-emacs-directory))

(use-package no-littering)

(setq custom-file
      (expand-file-name
       (format "emacs-custom-%s.el" (user-uid)) temporary-file-directory))
(load custom-file 'noerror 'nomessage)

(use-package try)
#+end_src

* Better Defaults

Everyone knows the default Emacs configuration is unusable. Here are some improvements.

#+begin_src emacs-lisp
(use-package emacs
  :hook
  ;; Auto reload dired buffers when the file system changes
  (dired-mode . auto-revert-mode)
  :custom
  (inhibit-startup-message t)
  (visible-bell t)
  (make-backup-files nil)
  :config
  ;; Minor Modes
  (menu-bar-mode 0)
  (tool-bar-mode 0)
  (scroll-bar-mode 0)

  (global-display-line-numbers-mode 1)
  (global-hl-line-mode 1)
  (ido-mode 1)
  (column-number-mode 1)

  ;; Revert buffers when the underlying file has changed
  (global-auto-revert-mode 1)

  (setq-default tab-width 2
                indent-tabs-mode nil))
#+end_src

* Text Editing

General text editing configurations shared across most major modes.

#+begin_src emacs-lisp
(use-package whitespace-cleanup-mode
  :config
  (global-whitespace-cleanup-mode 1))
#+end_src

* Enhancements

Add [[https://github.com/Alexander-Miller/treemacs][Treemacs]], because having a file explorer is nice.

#+begin_src emacs-lisp
(use-package treemacs
  :custom
  (treemacs-is-never-other-window t)
  (treemacs-width 30)
  :hook (treemacs-mode . (lambda() (display-line-numbers-mode -1)))
  :bind (("<f8>" . treemacs)
         ("C-<f8>" . treemacs-select-window)))

(use-package treemacs-icons-dired
  :after treemacs dired
  :config (treemacs-icons-dired-mode))

(use-package treemacs-magit
  :after treemacs magit)
#+end_src

* Org

Make sure code blocks mirror the language Major Mode.

#+begin_src emacs-lisp
(use-package org
  :hook (org-mode . visual-line-mode)
  :custom
  ;; Code blocks
  (org-src-preserve-indentation t)
  (org-src-tab-acts-natively t)
  (org-src-fontify-natively t)
  ;; org-edit-special (C-c ')
  (org-src-window-setup 'current-window)
  :config
  ;; org-insert-structure-template (C-c C-,)
  (add-to-list 'org-structure-template-alist '("se" . "src emacs-lisp")))
#+end_src

* Web

Use default browser environment variable if it exists.

#+begin_src emacs-lisp
(if-let ((browser (getenv "BROWSER")))
    (setq browse-url-generic-program (executable-find browser)
          browse-url-browser-function 'browse-url-generic))
#+end_src

* Development

Configurations for dev tools and programming languages.

** Git

[[https://magit.vc/manual/magit/][Magit]] is the de facto standard Git client for Emacs.

#+begin_src emacs-lisp
(use-package magit)
#+end_src

** APIs

Add [[https://github.com/tkf/emacs-request][request]] and [[https://github.com/pashky/restclient.el][restclient]] to make working with APIs fast and easy.

#+begin_src emacs-lisp
(use-package request)
(use-package restclient)
#+end_src

** General Configs

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

(use-package rainbow-mode
  :hook
  (emacs-lisp-mode . rainbow-mode)
  (help-mode . rainbow-mode)
  (org-mode . rainbow-mode))

(use-package company)
#+end_src

** Languages

Language specific configurations.

*** Emacs Lisp

#+begin_src emacs-lisp
(add-hook 'emacs-lisp-mode-hook 'company-mode)

(use-package helpful
  :bind (("C-h f" . helpful-callable)
         ("C-h v" . helpful-variable)
         ("C-h o" . helpful-symbol)
         ("C-h C" . helpful-command)
         ("C-c C-d" . helpful-at-point)))
#+end_src

*** Shell

Most modern style guides recommend using [[https://github.com/koalaman/shellcheck][ShellCheck]]. This will need to be installed for [[https://github.com/federicotdn/flymake-shellcheck][flymake-shellcheck]] to work.

#+begin_src emacs-lisp
(use-package flymake-shellcheck
  :commands flymake-shellcheck-load
  :init (add-hook 'sh-mode-hook 'flymake-shellcheck-load))

;; set tab width
(setq sh-basic-offset 2)
#+end_src

* Theme

Keep it simple with [[https://github.com/doomemacs/themes][doom-themes]], [[https://github.com/seagle0128/doom-modeline][doom-modeline]] and [[https://github.com/domtronn/all-the-icons.el][all-the-icons]].
Be sure to run =M-x all-the-icons-install-fonts=.

#+begin_src emacs-lisp
(use-package doom-themes
  :custom
  (doom-themes-enable-bold t)
  (doom-themes-enable-italic t)
  (doom-themes-treemacs-theme "doom-colors")
  :config
  (load-theme 'doom-material-dark t)

  (doom-themes-visual-bell-config)
  (doom-themes-org-config)
  (doom-themes-treemacs-config))

(use-package doom-modeline
  :init (doom-modeline-mode 1))

(use-package all-the-icons
  :if (display-graphic-p))
#+end_src
