#!/bin/sh
#
# Install .emacs.d symlink in home directory.
# Backup existing folder to .emacs.d.backup if it exists.

emacs_d=$HOME/.emacs.d

if [ -e $emacs_d ] && [ ! -L "$emacs_d" ]; then
  mv "$emacs_d" "$emacs_d.backup"
fi

ln -Tsf "$(pwd)" "$HOME/.emacs.d"
